/// Relation digest binding the canonical PVM ACE circuit into the Fiat-Shamir transcript.
///
/// Regenerated by `pvm-constants-regen`; must match `PVM_RELATION_DIGEST` in
/// `miden-precompiles-verifier`'s `ace_constants.rs`.
#[rustfmt::skip]
pub const PVM_RELATION_DIGEST: [u64; 4] = [
    4446998535751267906,
    846455477672247373,
    7053340542946749351,
    5541321162928849377,
];
