/// Relation digest binding the canonical PVM ACE circuit into the Fiat-Shamir transcript.
///
/// Regenerated by `pvm-constants-regen`; must match `PVM_RELATION_DIGEST` in
/// `miden-precompiles-verifier`'s `ace_constants.rs`.
#[rustfmt::skip]
pub const PVM_RELATION_DIGEST: [u64; 4] = [
    3361698354073062026,
    4986952299538528908,
    3943855628436279425,
    1268933755884603674,
];
