/// Relation digest binding the canonical PVM ACE circuit into the Fiat-Shamir transcript.
///
/// Regenerated by `pvm-constants-regen`; must match `PVM_RELATION_DIGEST` in
/// `miden-precompiles-verifier`'s `ace_constants.rs`.
#[rustfmt::skip]
pub const PVM_RELATION_DIGEST: [u64; 4] = [
    1721476589381610803,
    17304900310411707620,
    14938047691760164133,
    6942537445238582033,
];
