#############################  Exclusions  #############################

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
    '^file:///.*test-utils',                    # Missing test-utils directory
    '^file:///.*stdlib/docs/sys\.md',           # Missing stdlib docs file
    '^file:///.*\.png$',                        # Image files
    '^file:///.*\.svg$',                        # SVG files
]

# Exclude these filesystem paths from getting checked.
exclude_path = [
    ".git/*",
    "node_modules/*",
    "target/*",
]

