[package]
name = "miden-test-utils"
version = "0.35.0"
description = "Test utilities for Miden VM programs"
readme = "README.md"
categories = ["development-tools::testing", "no-std"]
keywords = ["miden", "test", "virtual-machine"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[features]
default = ["std"]
arbitrary = ["dep:proptest", "miden-assembly/testing", "miden-core/testing"]
std = [
    "dep:env_logger",
    "dep:pretty_assertions",
    "dep:test-case",
    "miden-assembly/std",
    "miden-core/std",
    "miden-processor/std",
    "miden-prover/std",
    "miden-verifier/std",
    "proptest?/std",
]
testing = ["arbitrary"]

[dependencies]
miden-air.workspace = true
miden-assembly.workspace = true
miden-assembly-syntax.workspace = true
miden-core.workspace = true
miden-mast-package.workspace = true
miden-processor = { workspace = true, features = ["testing"] }
miden-prover.workspace = true
miden-verifier.workspace = true
proptest = { workspace = true, optional = true }
test-case = { version = "3.2", optional = true }
pretty_assertions = { workspace = true, features = ["std"], optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
env_logger = { workspace = true, optional = true }
