name: 'Rust Build Space Optimizer'
description: 'Maximizes build space for Rust projects by removing unnecessary tools'

runs:
  using: 'composite'
  steps:
    - name: Maximize build space for Rust
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'