[package]
name = "miden-debug-types"
version = "0.30.0"
description = "Core source-level debugging information types used throughout the Miden toolchain"
documentation = "https://docs.rs/miden-debug-types"
readme = "README.md"
categories = ["compilers", "no-std"]
keywords = ["debugging", "debuginfo", "span"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.cargo-shear]
ignored = ["serde_json"]

[features]
default = ["std"]
std = [
    "miden-diagnostics/std",
    "proptest?/std",
    "serde/std",
]
arbitrary = ["std", "dep:proptest"]
serde = ["dep:serde"]

[dependencies]
# Miden dependencies
miden-serde-utils.workspace = true
miden-diagnostics.workspace = true

# External dependencies
proptest = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
zerocopy.workspace = true

[dev-dependencies]
miden-test-serialization-macros.workspace = true
proptest.workspace = true
serde_json.workspace = true
