[package]
name = "miden-processor"
version = "0.6.0"
description = "Miden VM processor"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["emulators", "no-std"]
keywords = ["miden", "virtual-machine"]
edition = "2021"
rust-version = "1.67"

[lib]
bench = false
doctest = false

[features]
concurrent = ["winter-prover/concurrent", "std"]
default = ["std"]
internals = []
std = ["vm-core/std", "winter-prover/std", "log/std"]

[dependencies]
log = "0.4.14"
vm-core = { package = "miden-core", path = "../core", version = "0.6", default-features = false }
miden-air = { package = "miden-air", path = "../air", version = "0.6", default-features = false }
winter-prover = { package = "winter-prover", git = "https://github.com/facebook/winterfell.git", branch = "main", default-features = false }

[dev-dependencies]
logtest = { version = "2.0", default-features = false  }
miden-assembly = { package = "miden-assembly", path = "../assembly", version = "0.6", default-features = false }
rand-utils = { package = "winter-rand-utils", git = "https://github.com/facebook/winterfell.git", branch = "main" }
test-utils = { package = "miden-test-utils", path = "../test-utils", version = "0.1" }
winter-fri = { package = "winter-fri", git = "https://github.com/facebook/winterfell.git", branch = "main" }
winter-utils = { package = "winter-utils", git = "https://github.com/facebook/winterfell.git", branch = "main" }
