[package]
name = "distaff-processor"
version = "0.1.0"
description = "TODO"
authors = ["distaff contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/distaff"
categories = ["TODO"]
keywords = ["TODO"]
edition = "2018"

[lib]
bench = false

[dependencies]
vm-core = { package = "distaff-core", path = "../core" }
winter-prover = { package = "winter-prover", version = "0.2"}

[dev-dependencies]
rand-utils = { package = "winter-rand-utils", version = "0.2" }
