[package]
name = "distaff-processor"
version = "0.1.0"
description = "Distaff VM processor"
authors = ["distaff contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/distaff"
categories = ["emulators", "no-std"]
keywords = ["distaff", "virtual-machine"]
edition = "2018"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std", "winterfell/std"]

[dependencies]
vm-core = { package = "distaff-core", path = "../core", default-features = false }
winterfell = { package = "winter-prover", version = "0.2", default-features = false }

[dev-dependencies]
rand-utils = { package = "winter-rand-utils", version = "0.2" }
