[package]
name = "miden-stdlib"
version = "0.4.0"
description = "Miden VM standard library"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["cryptography", "mathematics"]
keywords = ["miden", "program", "stdlib"]
edition = "2021"
rust-version = "1.67"

[lib]
bench = false
doctest = false

[[test]]
name = "stdlib"
path = "tests/main.rs"

[dependencies]
assembly = { package = "miden-assembly", default-features = false, path = "../assembly", version = "0.5" }

[dev-dependencies]
processor = { package = "miden-processor", path = "../processor", version = "0.5", default-features = false }
vm-core = { package = "miden-core", path = "../core", version = "0.5", default-features = false }
rand-utils = { package = "winter-rand-utils", version = "0.5" }
blake3 = "1.3"

[build-dependencies]
assembly = { package = "miden-assembly", path = "../assembly", version = "0.5" }
