[package]
name = "miden-stdlib"
version = "0.3.0"
description = "Miden VM standard library"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["cryptography", "mathematics"]
keywords = ["miden", "program", "stdlib"]
edition = "2021"
rust-version = "1.65"

[lib]
bench = false
doctest = false

[dependencies]
vm-core = { package = "miden-core", default-features = false, path = "../core", version = "0.4" }
vm-assembly = { package = "miden-assembly", default-features = false, path = "../assembly", version = "0.4" }

[build-dependencies]
vm-assembly = { package = "miden-assembly", default-features = false, path = "../assembly", version = "0.4" }
