[package]
name = "miden-project"
version = "0.30.0"
description = "Interface for working with Miden projects"
documentation = "https://docs.rs/miden-project"
readme = "README.md"
categories = ["compilers", "no-std"]
keywords = ["project", "miden"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[features]
default = ["std"]
arbitrary = ["std", "dep:proptest", "dep:proptest-derive", "miden-assembly-syntax/arbitrary"]
resolver = ["std", "miden-package-registry/resolver"]
std = ["miden-assembly-syntax/std", "miden-diagnostics/std", "miden-package-registry/std", "miden-package-registry/resolver", "proptest?/std", "serde?/std", "tempfile/getrandom", "thiserror/std", "toml/std"]
serde = ["dep:serde", "dep:serde-untagged", "miden-assembly-syntax/serde", "miden-debug-types/serde", "miden-mast-package/serde", "miden-package-registry/serde", "toml/serde", "toml/parse", "toml/display"]

[dependencies]
miden-assembly-syntax.workspace = true
miden-core.workspace = true
miden-debug-types.workspace = true
miden-diagnostics.workspace = true
miden-mast-package.workspace = true
miden-package-registry.workspace = true
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde-untagged = { workspace = true, optional = true }
thiserror.workspace = true
toml = { workspace = true, features = ["serde"] }

[dev-dependencies]
miden-core.workspace = true
miden-mast-package = { workspace = true, features = ["arbitrary"] }
miden-test-serialization-macros.workspace = true
proptest.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml = { workspace = true, features = ["std", "serde", "parse"] }


[package.metadata.cargo-shear]
ignored = ["proptest", "serde_json"]
