[package]
name = "distaff-core"
version = "0.1.0"
description = "TODO"
authors = ["distaff contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/distaff"
categories = ["TODO"]
keywords = ["TODO"]
edition = "2018"

[lib]
bench = false

[features]
default = ["std"]
std = ["math/std", "winter-utils/std"]

[dependencies]
math = { package = "winter-math", version = "0.2", default-features = false }
winter-utils = { package = "winter-utils", version = "0.2", default-features = false }
