[package]
name = "miden-core"
version = "0.10.0"
description = "Miden VM core components"
documentation = "https://docs.rs/miden-core/0.10.0"
categories = ["emulators", "no-std"]
keywords = ["instruction-set", "miden", "program"]
readme.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
bench = false
doctest = false

[features]
default = ["std"]
diagnostics = ["dep:miette"]
std = [
    "dep:parking_lot",
    "memchr/std",
    "miden-crypto/std",
    "miden-formatting/std",
    "math/std",
    "winter-utils/std",
    "thiserror/std",
]

[dependencies]
math = { package = "winter-math", version = "0.9", default-features = false }
memchr = { version = "2.7", default-features = false }
miden-crypto = { git = "https://github.com/0xPolygonMiden/crypto", branch = "next", default-features = false }
miden-formatting = { version = "0.1", default-features = false }
miette = { version = "7.1.0", git = "https://github.com/bitwalker/miette", branch = "no-std", default-features = false, features = [
    "fancy-no-syscall",
    "derive",
], optional = true }
lock_api = { version = "0.4", features = ["arc_lock"] }
parking_lot = { version = "0.12", optional = true }
num-derive = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
thiserror = { version = "1.0", git = "https://github.com/bitwalker/thiserror", branch = "no-std", default-features = false }
winter-utils = { package = "winter-utils", version = "0.9", default-features = false }

[dev-dependencies]
proptest = "1.3"
rand_utils = { version = "0.9", package = "winter-rand-utils" }
