[package]
name = "miden"
version = "0.1.0"
description="Miden virtual machine"
authors = ["miden contributors"]
readme="README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/miden"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "stark", "virtual-machine", "zkp"]
edition = "2018"

[lib]
name = "miden"
path = "src/lib.rs"
bench = false
doctest = false

[features]
concurrent = ["prover/concurrent", "std"]
default = ["std"]
std = ["air/std", "assembly/std", "hex/std", "processor/std", "prover/std", "verifier/std"]

[dependencies]
air = { package = "miden-air", path = "../air", version = "0.1", default-features = false }
assembly = { package = "miden-assembly", path = "../assembly", version = "0.1", default-features = false }
processor = { package = "miden-processor", path = "../processor", version = "0.1", default-features = false }
prover = { package = "winter-prover", version = "0.3", default-features = false }
hex = { version = "0.4", optional = true }
log = { version = "0.4", default-features = false }
verifier = { package = "miden-verifier", path = "../verifier", version = "0.1", default-features = false }
