[package]
name = "distaff-assembly"
version = "0.1.0"
description = "Distaff VM assembly language"
authors = ["distaff contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/distaff"
categories = ["compilers", "no-std"]
keywords = ["assembler", "assembly", "distaff", "language"]
edition = "2018"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std", "winter-utils/std"]

[dependencies]
vm-core = { package = "distaff-core", path = "../core", default-features = false }
winter-utils = { package = "winter-utils", version = "0.2", default-features = false }
