[package]
name = "distaff-assembly"
version = "0.1.0"
description = "TODO"
authors = ["distaff contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/distaff"
categories = ["TODO"]
keywords = ["TODO"]
edition = "2018"

[lib]
bench = false

[dependencies]
processor = { path = "../processor", package = "distaff-processor" }
	