pub mod bus;

use miden_core::field::PrimeCharacteristicRing;
use miden_crypto::stark::air::MidenAirBuilder;

use crate::MainTraceRow;

pub fn enforce_ace_chiplet_constraints<AB>(
    builder: &mut AB,
    local: &MainTraceRow<AB::Var>,
    next: &MainTraceRow<AB::Var>,
) where
    AB: MidenAirBuilder,
{
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (local.chiplets[4].clone().into() * local.chiplets[4].clone().into() - local.chiplets[4].clone().into()));
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (local.chiplets[5].clone().into() * local.chiplets[5].clone().into() - local.chiplets[5].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * next.chiplets[3].clone().into() * local.chiplets[4].clone().into());
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[3].clone().into()) * local.chiplets[4].clone().into() * next.chiplets[4].clone().into());
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * local.chiplets[4].clone().into() * local.chiplets[5].clone().into());
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - local.chiplets[4].clone().into()) * local.chiplets[5].clone().into() * (AB::Expr::ONE - next.chiplets[5].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * ((AB::Expr::ONE - next.chiplets[3].clone().into()) * local.chiplets[4].clone().into() + next.chiplets[3].clone().into() - (AB::Expr::ONE - next.chiplets[3].clone().into()) * local.chiplets[4].clone().into() * next.chiplets[3].clone().into()) * (AB::Expr::ONE - local.chiplets[5].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - local.chiplets[5].clone().into()) * ((AB::Expr::ONE - next.chiplets[5].clone().into()) * (next.chiplets[16].clone().into() - (next.chiplets[10].clone().into() + AB::Expr::ONE)) + next.chiplets[10].clone().into() + AB::Expr::ONE - local.chiplets[16].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[4].clone().into()) * (next.chiplets[6].clone().into() - local.chiplets[6].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[4].clone().into()) * (next.chiplets[8].clone().into() - local.chiplets[8].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[4].clone().into()) * (next.chiplets[7].clone().into() - (local.chiplets[7].clone().into() + AB::Expr::from_u64(4) * (AB::Expr::ONE - local.chiplets[5].clone().into()) + local.chiplets[5].clone().into())));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[3].clone().into()) * (AB::Expr::ONE - next.chiplets[4].clone().into()) * (local.chiplets[10].clone().into() - (next.chiplets[10].clone().into() + (AB::Expr::ONE - local.chiplets[5].clone().into()).double() + local.chiplets[5].clone().into())));
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * (AB::Expr::ONE - local.chiplets[5].clone().into()) * (local.chiplets[13].clone().into() - (local.chiplets[10].clone().into() - AB::Expr::ONE)));
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * local.chiplets[5].clone().into() * local.chiplets[9].clone().into() * (local.chiplets[9].clone().into() - AB::Expr::ONE) * (local.chiplets[9].clone().into() + AB::Expr::ONE));
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * local.chiplets[5].clone().into() * (local.chiplets[9].clone().into() * local.chiplets[9].clone().into() * (local.chiplets[14].clone().into() + local.chiplets[9].clone().into() * local.chiplets[17].clone().into() - (local.chiplets[14].clone().into() * local.chiplets[17].clone().into() - local.chiplets[15].clone().into().double() * local.chiplets[18].clone().into())) + local.chiplets[14].clone().into() * local.chiplets[17].clone().into() - local.chiplets[15].clone().into().double() * local.chiplets[18].clone().into() - local.chiplets[11].clone().into()));
    builder.assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * local.chiplets[5].clone().into() * (local.chiplets[9].clone().into() * local.chiplets[9].clone().into() * (local.chiplets[15].clone().into() + local.chiplets[9].clone().into() * local.chiplets[18].clone().into() - ((local.chiplets[17].clone().into() + local.chiplets[18].clone().into()) * (local.chiplets[14].clone().into() + local.chiplets[15].clone().into()) - local.chiplets[14].clone().into() * local.chiplets[17].clone().into())) + (local.chiplets[17].clone().into() + local.chiplets[18].clone().into()) * (local.chiplets[14].clone().into() + local.chiplets[15].clone().into()) - local.chiplets[14].clone().into() * local.chiplets[17].clone().into() - local.chiplets[12].clone().into()));
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * ((AB::Expr::ONE - next.chiplets[3].clone().into()) * next.chiplets[4].clone().into() + next.chiplets[3].clone().into() - (AB::Expr::ONE - next.chiplets[3].clone().into()) * next.chiplets[4].clone().into() * next.chiplets[3].clone().into()) * local.chiplets[11].clone().into());
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * ((AB::Expr::ONE - next.chiplets[3].clone().into()) * next.chiplets[4].clone().into() + next.chiplets[3].clone().into() - (AB::Expr::ONE - next.chiplets[3].clone().into()) * next.chiplets[4].clone().into() * next.chiplets[3].clone().into()) * local.chiplets[12].clone().into());
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * local.chiplets[2].clone().into() * (AB::Expr::ONE - local.chiplets[3].clone().into()) * ((AB::Expr::ONE - next.chiplets[3].clone().into()) * next.chiplets[4].clone().into() + next.chiplets[3].clone().into() - (AB::Expr::ONE - next.chiplets[3].clone().into()) * next.chiplets[4].clone().into() * next.chiplets[3].clone().into()) * local.chiplets[10].clone().into());
    builder.when_transition().assert_zero(local.chiplets[0].clone().into() * local.chiplets[1].clone().into() * (AB::Expr::ONE - local.chiplets[2].clone().into()) * next.chiplets[2].clone().into() * (next.chiplets[4].clone().into() - AB::Expr::ONE));
}
