use std::{
    path::{Path, PathBuf},
    time::Instant,
};

use clap::Parser;
use miden_assembly::diagnostics::{IntoDiagnostic, Report, WrapErr};
use miden_core_lib::CoreLibrary;
use miden_processor::{DefaultHost, ExecutionOptions, FastProcessor};
use miden_vm::{HashFunction, Prover, internal::InputFile};

use super::{
    data::{Libraries, OutputFile, ProofFile},
    utils::{get_masm_program, get_masp_program, parse_byte_size},
};

#[derive(Debug, Clone, Parser)]
#[command(about = "Prove a Miden program")]
pub struct ProveCmd {
    /// Path to a .masm assembly file or a .masp package file
    #[arg(value_parser)]
    program_file: PathBuf,

    /// Number of cycles the program is expected to consume
    #[arg(short = 'e', long = "exp-cycles", default_value = "64")]
    expected_cycles: u32,

    /// Path to input file
    #[arg(short = 'i', long = "input", value_parser)]
    input_file: Option<PathBuf>,

    /// Paths to .masp library files
    #[arg(short = 'l', long = "libraries", value_parser)]
    library_paths: Vec<PathBuf>,

    /// Maximum number of cycles a program is allowed to consume
    #[arg(short = 'm', long = "max-cycles", default_value_t = ExecutionOptions::MAX_CYCLES)]
    max_cycles: u32,

    /// Maximum memory, in bytes, the prover may allocate (accepts suffixes: 512M, 32Gi)
    #[arg(
        long = "max-prover-memory",
        default_value_t = Prover::DEFAULT_MAX_PROVER_MEMORY_BYTES,
        value_parser = parse_byte_size
    )]
    max_prover_memory: u64,

    /// Number of outputs
    #[arg(short = 'n', long = "num-outputs", default_value = "16")]
    num_outputs: usize,

    /// Path to output file
    #[arg(short = 'o', long = "output", value_parser)]
    output_file: Option<PathBuf>,

    /// Path to proof file
    #[arg(short = 'p', long = "proof", value_parser)]
    proof_file: Option<PathBuf>,

    /// Specifies the hash function to be used
    /// Valid options: blake3-256, rpo, rpx, poseidon2
    #[arg(long = "hasher", default_value = "blake3-256")]
    hasher: String,

    /// Security level for execution proofs generated by the VM
    #[arg(short = 's', long = "security", default_value = "96bits")]
    security: String,

    /// Path to a file (.masm or .masp) containing the kernel to be loaded with the program
    #[arg(long = "kernel", value_parser)]
    kernel_file: Option<PathBuf>,
}

impl ProveCmd {
    pub fn get_execution_options(&self) -> Result<ExecutionOptions, Report> {
        ExecutionOptions::new(
            Some(self.max_cycles),
            self.expected_cycles,
            ExecutionOptions::DEFAULT_CORE_TRACE_FRAGMENT_SIZE,
        )
        .map_err(|err| Report::msg(format!("{err}")))
    }

    pub fn get_hash_fn(&self) -> Result<HashFunction, Report> {
        if self.security != "96bits" {
            return Err(Report::msg(format!(
                "{} is not a valid security setting. Currently only '96bits' is supported.",
                self.security
            )));
        }

        HashFunction::try_from(self.hasher.as_str()).map_err(|err| Report::msg(format!("{err}")))
    }
    pub fn execute(&self) -> Result<(), Report> {
        println!("===============================================================================");
        println!("Prove program: {}", self.program_file.display());
        println!("-------------------------------------------------------------------------------");

        // determine file type based on extension
        let ext = self
            .program_file
            .extension()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_lowercase();
        if !matches!(ext.as_str(), "masm" | "masp") {
            return Err(Report::msg("The provided file must have a .masm or .masp extension"));
        }

        // load libraries from files
        let libraries = Libraries::new(&self.library_paths)?;

        // validate kernel file if provided
        if let Some(ref kernel_path) = self.kernel_file
            && !kernel_path.is_file()
        {
            return Err(Report::msg(format!(
                "Kernel file `{}` must be a file.",
                kernel_path.display()
            )));
        }

        let input_data = InputFile::read(&self.input_file, &self.program_file)?;

        let host = DefaultHost::default().with_library(&CoreLibrary::default())?;
        // Use a single match expression to load the program.
        let (program, package_debug_info, entrypoint_source_node, mut host) = match ext.as_str() {
            "masp" => (get_masp_program(&self.program_file)?, None, None, host),
            "masm" => {
                let (program, package_debug_info, entrypoint_source_node, source_manager) =
                    get_masm_program(&self.program_file, &libraries, self.kernel_file.as_deref())?;
                let mut host = host.with_source_manager(source_manager);
                for library in libraries.libraries.iter().cloned() {
                    host.load_library(library)
                        .into_diagnostic()
                        .wrap_err("Failed to load library")?;
                }
                (program, package_debug_info, entrypoint_source_node, host)
            },
            _ => unreachable!("program file extension was validated above"),
        };

        let program_hash: [u8; 32] = program.hash().into();
        println!("Proving program with hash {}...", hex::encode(program_hash));
        let now = Instant::now();

        // fetch the stack and program inputs from the arguments
        let stack_inputs = input_data.parse_stack_inputs().map_err(Report::msg)?;
        let advice_inputs = input_data.parse_advice_inputs().map_err(Report::msg)?;

        let execution_options = self.get_execution_options()?;
        let hash_fn = self.get_hash_fn()?;

        // execute program and generate proof
        let processor =
            FastProcessor::new_with_options(stack_inputs, advice_inputs, execution_options)
                .map_err(|err| Report::msg(format!("{err}")))?;
        let witness = match (package_debug_info.as_ref(), entrypoint_source_node) {
            (Some(debug_info), Some(entrypoint_source_node_id)) => processor
                .execute_for_proving_with_package_debug_info_at_source_node_sync(
                    &program,
                    debug_info,
                    entrypoint_source_node_id,
                    &mut host,
                )
                .wrap_err("Failed to execute program")?,
            (Some(debug_info), None) => processor
                .execute_for_proving_with_package_debug_info_sync(&program, debug_info, &mut host)
                .wrap_err("Failed to execute program")?,
            (None, _) => processor
                .execute_for_proving_sync(&program, &mut host)
                .wrap_err("Failed to execute program")?,
        };
        let stack_outputs = *witness.claim().stack_outputs();
        let proof = Prover::new()
            .with_hash_fn(hash_fn)
            .with_max_prover_memory_bytes(self.max_prover_memory)
            .prove_full(witness)
            .map_err(|err| Report::msg(format!("Failed to prove program: {err}")))?;

        println!("Program proved in {} ms", now.elapsed().as_millis());

        // write proof to file
        ProofFile::write(proof, &self.proof_file, &self.program_file).map_err(Report::msg)?;

        // Whether the outputs path names the proof is a question only the filesystem can answer,
        // and only now that the proof exists: comparing file identity sees through symlinks, `..`
        // components, case-insensitive names, Unicode normalization and hard links in one step.
        let proof_path = self.resolved_proof_path();
        let output_path = self.output_file.clone().unwrap_or_else(|| self.default_output_path());
        if resolve_to_same_file(&output_path, &proof_path) {
            return Err(Report::msg(format!(
                "The outputs file `{}` would overwrite the proof file `{}`. The proof was kept; \
                 re-run with a different --proof or --output path to get the outputs.",
                output_path.display(),
                proof_path.display()
            )));
        }

        OutputFile::write(&stack_outputs, &output_path).map_err(Report::msg)?;

        // without --output the outputs file is not where the user is looking, so print the stack
        if self.output_file.is_none() {
            let stack = stack_outputs.get_num_elements(self.num_outputs).to_vec();
            println!("Output: {stack:?}");
        }

        Ok(())
    }

    /// Resolves the proof path the same way as ProofFile::write.
    fn resolved_proof_path(&self) -> PathBuf {
        ProofFile::resolve_path(&self.proof_file, &self.program_file)
    }

    /// Derives verify's default outputs path from the resolved proof path.
    fn default_output_path(&self) -> PathBuf {
        self.resolved_proof_path().with_extension("outputs")
    }
}

/// Returns true when both paths name the same existing file.
///
/// This runs after the proof has been written, so the proof side always exists. An outputs path
/// that cannot be opened names a file that does not exist yet, which therefore cannot be the proof.
fn resolve_to_same_file(output_path: &Path, proof_path: &Path) -> bool {
    same_file::is_same_file(output_path, proof_path).unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    fn prove_cmd(program_file: &str, proof_file: Option<&str>) -> ProveCmd {
        ProveCmd {
            program_file: PathBuf::from(program_file),
            expected_cycles: 64,
            input_file: None,
            library_paths: Vec::new(),
            max_cycles: ExecutionOptions::MAX_CYCLES,
            max_prover_memory: Prover::DEFAULT_MAX_PROVER_MEMORY_BYTES,
            num_outputs: 16,
            output_file: None,
            proof_file: proof_file.map(PathBuf::from),
            hasher: "blake3-256".to_string(),
            security: "96bits".to_string(),
            kernel_file: None,
        }
    }

    #[test]
    fn default_output_path_follows_the_program_when_no_proof_is_given() {
        assert_eq!(
            prove_cmd("dir/program.masm", None).default_output_path(),
            PathBuf::from("dir/program.outputs")
        );
    }

    #[test]
    fn default_output_path_follows_a_custom_proof_path() {
        assert_eq!(
            prove_cmd("dir/program.masm", Some("out/custom.proof")).default_output_path(),
            PathBuf::from("out/custom.outputs")
        );
    }

    #[test]
    fn default_output_path_handles_an_extensionless_proof_path() {
        assert_eq!(
            prove_cmd("dir/program.masm", Some("out/custom")).default_output_path(),
            PathBuf::from("out/custom.outputs")
        );
    }

    #[test]
    fn default_output_path_collides_with_a_proof_path_that_is_already_an_outputs_path() {
        assert_eq!(
            prove_cmd("dir/program.masm", Some("out/custom.outputs")).default_output_path(),
            PathBuf::from("out/custom.outputs")
        );
    }

    #[test]
    fn resolve_to_same_file_sees_through_a_symlinked_proof_path() {
        let dir = tempfile::tempdir().unwrap();
        let proof_path = dir.path().join("same.proof");
        fs::write(&proof_path, "proof").unwrap();

        #[cfg(unix)]
        {
            let alias_path = dir.path().join("alias.proof");
            std::os::unix::fs::symlink(&proof_path, &alias_path).unwrap();
            assert!(resolve_to_same_file(&alias_path, &proof_path));
        }

        // negative control: with `sub` missing there is nothing to resolve `..` against
        assert!(!resolve_to_same_file(&dir.path().join("./sub/../same.proof"), &proof_path));

        fs::create_dir(dir.path().join("sub")).unwrap();
        assert!(resolve_to_same_file(&dir.path().join("./sub/../same.proof"), &proof_path));
    }

    #[test]
    fn resolve_to_same_file_sees_through_a_hard_link() {
        let dir = tempfile::tempdir().unwrap();
        let proof_path = dir.path().join("same.proof");
        fs::write(&proof_path, "proof").unwrap();

        // negative control: a copy has the same contents but is a different file
        let copy_path = dir.path().join("copy.proof");
        fs::copy(&proof_path, &copy_path).unwrap();
        assert!(!resolve_to_same_file(&copy_path, &proof_path));

        let link_path = dir.path().join("link.proof");
        fs::hard_link(&proof_path, &link_path).unwrap();
        assert!(resolve_to_same_file(&link_path, &proof_path));
    }

    #[test]
    fn resolve_to_same_file_ignores_an_outputs_path_that_does_not_exist_yet() {
        let dir = tempfile::tempdir().unwrap();
        let proof_path = dir.path().join("same.proof");
        fs::write(&proof_path, "proof").unwrap();

        assert!(!resolve_to_same_file(&dir.path().join("same.outputs"), &proof_path));
    }
}
