name: 'Release-plz Action'
description: 'Runs release-plz with dry-run support and workflow synchronization'

inputs:
  dry-run:
    description: 'Whether to run in dry-run mode (true) or production mode (false)'
    required: false
    default: 'false'
  ref:
    description: 'Git ref to checkout (empty for default branch, "main" for production releases)'
    required: false
    default: ''
  verify-main-head:
    description: 'Whether to verify release is from main HEAD (security for production)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref || '' }}
    - name: Cleanup large tools for build space
      uses: ./.github/actions/cleanup-runner
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y jq
    - name: Update Rust toolchain
      shell: bash
      run: |
        rustup update --no-self-update
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-msrv
      shell: bash
      run: cargo install cargo-msrv
    - name: Cache rustup toolchains
      shell: bash
      run: rustup update
    - name: Check MSRV for workspace
      shell: bash
      run: |
        chmod +x scripts/check-msrv.sh
        ./scripts/check-msrv.sh
    - name: Verify release was triggered from main HEAD
      if: ${{ inputs.verify-main-head == 'true' }}
      shell: bash
      run: |
        # Ensure the release tag refers to the latest commit on main.
        # Compare the commit SHA that triggered the workflow with the HEAD of the branch we just
        # checked out (main).
        tag_sha="${{ github.sha }}"
        main_sha="$(git rev-parse HEAD)"

        echo "Tag points to:        $tag_sha"
        echo "Current main HEAD is: $main_sha"

        if [ "$tag_sha" != "$main_sha" ]; then
          echo "::error::The release tag was not created from the latest commit on main. Aborting."
          exit 1
        fi
        echo "Release tag matches main HEAD — continuing."
    - name: Run release-plz
      uses: release-plz/action@v0.5
      with:
        command: release ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}