# @generated by miden-core-lib-codegen. Do not edit by hand.
# Source template: {{TEMPLATE_PATH}}
# Regenerate with: {{REGENERATE_COMMAND}}

use miden::core::precompiles
use miden::core::precompiles::fields::{{BASE_FIELD_MODULE}}

# {{TITLE}} CURVE PRECOMPILE SUPPORT WRAPPERS
# ================================================================================================
# User-facing curve values are deferred node digests. A canonical point is one join-shaped VALUE
# node whose payload is `[X_OR_TRUE_DIGEST, Y_OR_TRUE_DIGEST]`:
#
# - affine point: X/Y are canonical {{BASE_FIELD_DESCRIPTION}} uint VALUE digests;
# - identity:     X = TRUE_DIGEST and Y = TRUE_DIGEST.
#
# Wrapper contract:
# - the ABI is uniform for affine curves: constructors and arithmetic wrappers register deferred
#   expressions and return digests; `eval`/`eval_digest` canonicalize expressions to VALUE nodes;
# - raw coordinate digests and raw VALUE payloads are checked at VALUE evaluation boundaries;
# - ADD/SUB/MSM operands are evaluated to canonical curve/scalar VALUE nodes before arithmetic;
# - invalid coordinates, wrong-domain coordinate digests, mixed identity payloads, and non-curve
#   digests fail during deferred registration/evaluation;
# - MSM (`mul_scalar`, `mul_scalar_generator`, `msm_mem`, `msm2`, `msm2_generator`) accepts a zero
#   scalar for any pair (contributing identity to the sum) and a repeated, or structurally
#   different but canonically equal, base across pairs; the result may itself be the identity
#   point. An identity VALUE is rejected as an MSM base, failing the same way the other invalid
#   cases above do.
#
# Notation used below:
# - DIGEST        = one word [d0, d1, d2, d3], d0 on top of the stack.
# - VALUE_TAG     = one word [PRECOMPILE_ID, VALUE_OP_ID, GROUP_PTR, 0].
# - OP_TAG(op_id) = one word [PRECOMPILE_ID, op_id, 0, 0] for ADD/SUB/EQ.
# - MSM_TAG       = one word [PRECOMPILE_ID, MSM_OP_ID, 0, 0].
# - POINT_VALUE   = `[X_OR_TRUE_DIGEST, Y_OR_TRUE_DIGEST]` under VALUE_TAG.

const PRECOMPILE_ID = {{PRECOMPILE_ID}}
const GROUP_PTR = {{GROUP_PTR}}
const VALUE_OP_ID = {{VALUE_OP_ID}}
const ADD_OP_ID = {{ADD_OP_ID}}
const SUB_OP_ID = {{SUB_OP_ID}}
const EQ_OP_ID = {{EQ_OP_ID}}
const MSM_OP_ID = {{MSM_OP_ID}}

# VALUE tags carry GROUP_PTR; ADD/SUB/EQ/MSM tags deliberately use zero in that slot.
const VALUE_TAG = {{VALUE_TAG}}
const ADD_TAG = {{ADD_TAG}}
const SUB_TAG = {{SUB_TAG}}
const EQ_TAG = {{EQ_TAG}}
const MSM_TAG = {{MSM_TAG}}

# Initial chaining words for the fixed node shapes in this module. Codegen derives each word from
# its matching tag as `init(selector, [payload_len, arg0, arg1])`.
const VALUE_INIT_CV = {{VALUE_INIT_CV}}
const ADD_INIT_CV = {{ADD_INIT_CV}}
const SUB_INIT_CV = {{SUB_INIT_CV}}
const EQ_INIT_CV = {{EQ_INIT_CV}}
const MSM_INIT_CV = {{MSM_INIT_CV}}
const MSM2_INIT_CV = {{MSM2_INIT_CV}}

# Registered digests for CurvePrecompile init constants.
const IDENTITY_DIGEST = {{IDENTITY_DIGEST}}
const GENERATOR_DIGEST = {{GENERATOR_DIGEST}}

#! Registers a fixed one-block expression using a codegen-paired tag and initial chaining word.
#! Input:  [CV, TAG, PAYLOAD_LO, PAYLOAD_HI, ...]
#! Output: [NODE_DIGEST, ...]
proc register_fixed_expr
    movdnw.3 movdnw.2
    # => [PAYLOAD_LO, PAYLOAD_HI, TAG, CV, ...]
    adv.register_deferred
    movupw.2 dropw
    # => [PAYLOAD_LO, PAYLOAD_HI, CV, ...]
    compress
    dropw dropw
end

#! Registers the fixed one-block VALUE node staged in memory.
#! Input:  [TAG, ptr, n_chunks=1, ...]
#! Output: [VALUE_DIGEST, ...]
proc register_value_mem_1
    adv.register_deferred_data
    dropw
    # => [ptr, n_chunks=1, ...]

    push.VALUE_INIT_CV padw padw
    # => [BLOCK_LO=0w, BLOCK_HI=0w, CV, ptr, n_chunks=1, ...]
    mem_stream compress
    dropw dropw
    movup.4 drop movup.4 drop
end

#! Registers the fixed two-block MSM node staged in memory.
#! Input:  [TAG, ptr, n_chunks=2, ...]
#! Output: [MSM_POINT_DIGEST, ...]
proc register_msm_mem_2
    adv.register_deferred_data
    dropw
    # => [ptr, n_chunks=2, ...]

    push.MSM2_INIT_CV padw padw
    # => [BLOCK_LO=0w, BLOCK_HI=0w, CV, ptr, n_chunks=2, ...]
    repeat.2
        mem_stream compress
    end
    dropw dropw
    movup.4 drop movup.4 drop
end

#! Constructs an affine curve VALUE node from two coordinate digests.
#! Input:  [X_DIGEST, Y_DIGEST, ...]
#! Output: [POINT_DIGEST, ...]
pub proc load_digest_pair
    push.VALUE_TAG push.VALUE_INIT_CV
    # => [CV(VALUE), TAG(VALUE), X_DIGEST, Y_DIGEST, ...]
    exec.register_fixed_expr
    # => [POINT_DIGEST, ...]
end

#! Loads two registered coordinate digests from memory, returning point digest and advanced pointer.
#! Input:  [ptr, ...]
#! Output: [POINT_DIGEST, ptr+8, ...]
#! Memory layout: ptr[0..4] = X_DIGEST, ptr[4..8] = Y_DIGEST.
pub proc load_digest_pair_mem_stream
    dup push.1 swap push.VALUE_TAG
    # => [TAG(VALUE), ptr, n_chunks=1, original_ptr, ...]
    exec.register_value_mem_1
    # => [POINT_DIGEST, original_ptr, ...]
    movup.4 add.8 movdn.4
    # => [POINT_DIGEST, ptr+8, ...]
end

#! Loads two registered coordinate digests from memory and returns the point digest.
#! Input:  [ptr, ...]
#! Output: [POINT_DIGEST, ...]
pub proc load_digest_pair_mem
    exec.load_digest_pair_mem_stream
    # => [POINT_DIGEST, ptr+8, ...]
    movup.4 drop
    # => [POINT_DIGEST, ...]
end

#! Loads two consecutive base-field elements from memory as an affine point.
#! Input:  [ptr, ...]
#! Output: [POINT_DIGEST, ptr+16, ...]
#! Memory layout: ptr[0..8] = X_U32[8], ptr[8..16] = Y_U32[8].
pub proc load_mem_stream
    # Load Y from ptr+8 while preserving the original ptr underneath.
    dup
    add.8
    exec.{{BASE_FIELD_MODULE}}::load_mem_stream
    # => [Y_DIGEST, ptr+16, ptr, ...]

    # Recover the original ptr, load X, and drop the intermediate ptr+8.
    movup.5
    # => [ptr, Y_DIGEST, ptr+16, ...]
    exec.{{BASE_FIELD_MODULE}}::load_mem_stream
    # => [X_DIGEST, ptr+8, Y_DIGEST, ptr+16, ...]
    movup.4 drop
    # => [X_DIGEST, Y_DIGEST, ptr+16, ...]

    exec.load_digest_pair
    # => [POINT_DIGEST, ptr+16, ...]
end

#! Loads two consecutive base-field elements from memory as an affine point.
#! Input:  [ptr, ...]
#! Output: [POINT_DIGEST, ...]
pub proc load_mem
    exec.load_mem_stream
    # => [POINT_DIGEST, ptr+16, ...]
    movup.4 drop
    # => [POINT_DIGEST, ...]
end

#! Pushes the registered digest of the curve identity point.
pub proc push_identity
    push.IDENTITY_DIGEST
end

#! Pushes the registered digest of the conventional curve generator.
pub proc push_generator
    push.GENERATOR_DIGEST
end

#! Registers `lhs + rhs` and returns the result expression digest.
#! Input:  [LHS_DIGEST, RHS_DIGEST, ...]
#! Output: [SUM_DIGEST, ...]
pub proc add
    push.ADD_TAG push.ADD_INIT_CV
    # => [CV(ADD), TAG(ADD), LHS_DIGEST, RHS_DIGEST, ...]
    exec.register_fixed_expr
    # => [SUM_DIGEST, ...]
end

#! Registers `lhs - rhs` and returns the result expression digest.
#! Input:  [LHS_DIGEST, RHS_DIGEST, ...]
#! Output: [DIFF_DIGEST, ...]
pub proc sub
    push.SUB_TAG push.SUB_INIT_CV
    # => [CV(SUB), TAG(SUB), LHS_DIGEST, RHS_DIGEST, ...]
    exec.register_fixed_expr
    # => [DIFF_DIGEST, ...]
end


#! Registers `[k]point` for a scalar-field digest.
#! Input:  [POINT_DIGEST, SCALAR_DIGEST, ...]
#! Output: [PRODUCT_POINT_DIGEST, ...]
pub proc mul_scalar
    push.MSM_TAG push.MSM_INIT_CV
    # => [CV(MSM), TAG(MSM), POINT_DIGEST, SCALAR_DIGEST, ...]
    exec.register_fixed_expr
    # => [PRODUCT_POINT_DIGEST, ...]
end

#! Registers `[k]GENERATOR` for a scalar-field digest.
#! Input:  [SCALAR_DIGEST, ...]
#! Output: [PRODUCT_POINT_DIGEST, ...]
pub proc mul_scalar_generator
    push.GENERATOR_DIGEST
    # => [GENERATOR_DIGEST, SCALAR_DIGEST, ...]
    exec.mul_scalar
    # => [PRODUCT_POINT_DIGEST, ...]
end

#! Registers an MSM PairList staged in memory.
#! Input:  [ptr, n, ...]
#! Output: [MSM_POINT_DIGEST, ...]
#! Memory layout: pair i at ptr + 8*i is `[POINT_DIGEST, SCALAR_DIGEST]`.
pub proc msm_mem
    push.MSM_TAG
    # => [TAG(MSM), ptr, n, ...]
    exec.precompiles::register_mem
    # => [MSM_POINT_DIGEST, ...]
end

#! Registers a two-pair MSM from stack operands.
#! Input:  [POINT0_DIGEST, SCALAR0_DIGEST, POINT1_DIGEST, SCALAR1_DIGEST, ...]
#! Output: [MSM_POINT_DIGEST, ...]
@locals(16)
pub proc msm2
    loc_storew_le.0 dropw
    loc_storew_le.4 dropw
    loc_storew_le.8 dropw
    loc_storew_le.12 dropw
    push.2 locaddr.0
    # => [ptr, n=2, ...]
    push.MSM_TAG
    # => [TAG(MSM), ptr, n=2, ...]
    exec.register_msm_mem_2
    # => [MSM_POINT_DIGEST, ...]
end

#! Registers `[scalar0]GENERATOR + [scalar1]point1` as a two-pair MSM.
#! Input:  [SCALAR0_DIGEST, SCALAR1_DIGEST, POINT1_DIGEST, ...]
#! Output: [MSM_POINT_DIGEST, ...]
pub proc msm2_generator
    push.GENERATOR_DIGEST
    # => [GENERATOR_DIGEST, SCALAR0_DIGEST, SCALAR1_DIGEST, POINT1_DIGEST, ...]
    movupw.3 movdnw.2
    # => [GENERATOR_DIGEST, SCALAR0_DIGEST, POINT1_DIGEST, SCALAR1_DIGEST, ...]
    exec.msm2
    # => [MSM_POINT_DIGEST, ...]
end

#! Asserts two curve expressions are equal by logging an EQ predicate into the deferred root.
#! Input:  [LHS_DIGEST, RHS_DIGEST, ...]
#! Output: [...]
pub proc assert_eq
    push.EQ_TAG push.EQ_INIT_CV
    # => [CV(EQ), TAG(EQ), LHS_DIGEST, RHS_DIGEST, ...]
    exec.register_fixed_expr
    # => [EQ_DIGEST, ...]
    exec.precompiles::log_deferred
    # => [...]
end

#! Evaluates a curve expression and binds the advised canonical VALUE payload to the input digest.
#! Input:  [POINT_EXPR_DIGEST, ...]
#! Output: [POINT_VALUE_DIGEST, X_OR_TRUE_DIGEST, Y_OR_TRUE_DIGEST, ...]
#! Advice is untrusted. This wrapper re-hashes the advised VALUE payload with the registered VALUE_TAG and
#! logs `eq(EXPR_DIGEST, VALUE_DIGEST)` before returning the value digest and coordinate digests.
pub proc eval
    adv.evaluate_deferred_payload
    # => [EXPR_DIGEST, ...]

    # Bring the VALUE payload onto the stack in join order.
    adv_pushw adv_pushw
    # => [X_OR_TRUE_DIGEST, Y_OR_TRUE_DIGEST, EXPR_DIGEST, ...]

    # Derive VALUE_DIGEST while preserving both payload words for the return.
    dupw.1 dupw.1
    # => [X, Y, X, Y, EXPR_DIGEST, ...]
    push.VALUE_TAG push.VALUE_INIT_CV
    # => [CV(VALUE), TAG(VALUE), X, Y, X, Y, EXPR_DIGEST, ...]
    exec.register_fixed_expr
    # => [VALUE_DIGEST, X, Y, EXPR_DIGEST, ...]

    # Preserve VALUE_DIGEST for the return while logging eq(EXPR_DIGEST, VALUE_DIGEST).
    movupw.3
    # => [EXPR_DIGEST, VALUE_DIGEST, X, Y, ...]
    dupw.1 movdnw.2
    # => [EXPR_DIGEST, VALUE_DIGEST, VALUE_DIGEST, X, Y, ...]
    push.EQ_TAG push.EQ_INIT_CV
    # => [CV(EQ), TAG(EQ), EXPR_DIGEST, VALUE_DIGEST, VALUE_DIGEST, X, Y, ...]
    exec.register_fixed_expr
    # => [EQ_DIGEST, VALUE_DIGEST, X, Y, ...]
    exec.precompiles::log_deferred
    # => [VALUE_DIGEST, X, Y, ...]
end

#! Evaluates a curve expression and binds the advised canonical VALUE payload to the input digest.
#! Input:  [POINT_EXPR_DIGEST, ...]
#! Output: [POINT_VALUE_DIGEST, ...]
#! Advice is untrusted. This is the digest-only form of `eval` for callers that do not need the
#! coordinate digests.
proc eval_digest
    adv.evaluate_deferred_payload
    # => [EXPR_DIGEST, ...]

    # Derive the VALUE digest from the advised join payload.
    adv_pushw adv_pushw
    # => [X_OR_TRUE_DIGEST, Y_OR_TRUE_DIGEST, EXPR_DIGEST, ...]
    push.VALUE_TAG push.VALUE_INIT_CV
    # => [CV(VALUE), TAG(VALUE), X_OR_TRUE_DIGEST, Y_OR_TRUE_DIGEST, EXPR_DIGEST, ...]
    exec.register_fixed_expr
    # => [VALUE_DIGEST, EXPR_DIGEST, ...]

    # Log eq(VALUE_DIGEST, EXPR_DIGEST) while preserving VALUE_DIGEST for the return. EQ predicate
    # operands are semantically commutative, so this order avoids an extra swap.
    dupw movdnw.2
    # => [VALUE_DIGEST, EXPR_DIGEST, VALUE_DIGEST, ...]
    push.EQ_TAG push.EQ_INIT_CV
    # => [CV(EQ), TAG(EQ), VALUE_DIGEST, EXPR_DIGEST, VALUE_DIGEST, ...]
    exec.register_fixed_expr
    # => [EQ_DIGEST, VALUE_DIGEST, ...]
    exec.precompiles::log_deferred
    # => [VALUE_DIGEST, ...]
end

#! Evaluates two curve expression digests and returns whether their canonical VALUE digests match.
#! Input:  [LHS_DIGEST, RHS_DIGEST, ...]
#! Output: [is_equal, ...]
pub proc is_eq
    exec.eval_digest
    # => [LHS_VALUE_DIGEST, RHS_DIGEST, ...]
    swapw
    # => [RHS_DIGEST, LHS_VALUE_DIGEST, ...]
    exec.eval_digest
    # => [RHS_VALUE_DIGEST, LHS_VALUE_DIGEST, ...]
    exec.precompiles::word_eq
    # => [is_equal, ...]
end

#! Evaluates a curve expression digest and returns whether its canonical VALUE digest matches target.
#! Input:  [TARGET_DIGEST, EXPR_DIGEST, ...]
#! Output: [is_equal, ...]
pub proc is_eq_digest
    swapw
    # => [EXPR_DIGEST, TARGET_DIGEST, ...]
    exec.eval_digest
    # => [VALUE_DIGEST, TARGET_DIGEST, ...]
    exec.precompiles::word_eq
    # => [is_equal, ...]
end

#! Evaluates a curve expression and returns whether it is the identity point.
#! Input:  [POINT_DIGEST, ...]
#! Output: [is_identity, ...]
pub proc is_identity
    push.IDENTITY_DIGEST
    # => [IDENTITY_DIGEST, POINT_DIGEST, ...]
    exec.is_eq_digest
    # => [is_identity, ...]
end

#! Asserts a curve expression equals a target curve expression by logging an EQ predicate.
#! Input:  [TARGET_DIGEST, EXPR_DIGEST, ...]
#! Output: [...]
pub proc assert_eq_digest
    exec.assert_eq
end

#! Asserts a curve expression is the identity point.
#! Input:  [POINT_DIGEST, ...]
#! Output: [...]
pub proc assert_identity
    push.IDENTITY_DIGEST
    # => [IDENTITY_DIGEST, POINT_DIGEST, ...]
    exec.assert_eq_digest
end

#! Evaluates a curve expression and asserts it is not the identity point.
#! Input:  [POINT_DIGEST, ...]
#! Output: [...]
pub proc assert_not_identity
    exec.eval_digest
    # => [VALUE_DIGEST, ...]
    push.IDENTITY_DIGEST
    # => [IDENTITY_DIGEST, VALUE_DIGEST, ...]
    exec.precompiles::word_eq
    # => [is_identity, ...]
    assertz
end

#! Negates a point by computing O - P.
#! Input:  [POINT_DIGEST, ...]
#! Output: [NEG_POINT_DIGEST, ...]
pub proc neg
    push.IDENTITY_DIGEST
    # => [IDENTITY_DIGEST, POINT_DIGEST, ...]
    exec.sub
    # => [NEG_POINT_DIGEST, ...]
end

#! Doubles a point by computing P + P.
#! Input:  [POINT_DIGEST, ...]
#! Output: [DOUBLE_POINT_DIGEST, ...]
pub proc double
    dupw
    # => [POINT_DIGEST, POINT_DIGEST, ...]
    exec.add
    # => [DOUBLE_POINT_DIGEST, ...]
end
