# Runs bench related jobs.

name: bench

permissions:
  contents: read

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  bench:
    name: Bench on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Bench for all features
        run: |
          rustup +stable update --no-self-update
          rustup default stable
          make check-bench
