# Runs bench related jobs.

name: bench

permissions:
  contents: read

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  bench:
    name: Bench on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bench for all features
        run: |
          rustup +stable update --no-self-update
          rustup default stable
          make check-bench
