name: miden book

on:
  push:
    branches: [main, next]

jobs:
  deploy:
    name: Deploy miden-vm mdbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install katex, alerts and linkcheck
        run: |
          rustup update --no-self-update stable
          cargo +stable install mdbook-katex mdbook-linkcheck mdbook-alerts

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build miden book
        run: mdbook build docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book/html
