name: Book

on:
  push:
    branches: [main, next]
  pull_request:
    paths:
      - 'src/docs/SUMMARY.md'
      - 'src/docs/IMPORTED.md'

jobs:
  check-files:
    name: Check Interdependent Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if SUMMARY.md and IMPORTED.md are modified together
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            # For push events, compare with the previous commit
            BASE_SHA=${{ github.event.before }}
            HEAD_SHA=${{ github.event.after }}
          fi

          # Check which files were modified
          SUMMARY_CHANGED=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -q "src/docs/SUMMARY.md" && echo "true" || echo "false")
          IMPORTED_CHANGED=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -q "src/docs/IMPORTED.md" && echo "true" || echo "false")

          # If one file changed and the other didn't, fail the check
          if [[ "$SUMMARY_CHANGED" == "true" && "$IMPORTED_CHANGED" == "false" ]]; then
            echo "Error: src/docs/SUMMARY.md was modified but src/docs/IMPORTED.md was not. Please update both files together."
            exit 1
          fi

          if [[ "$SUMMARY_CHANGED" == "false" && "$IMPORTED_CHANGED" == "true" ]]; then
            echo "Error: src/docs/IMPORTED.md was modified but src/docs/SUMMARY.md was not. Please update both files together."
            exit 1
          fi

          echo "Both files were either modified together or not modified at all. Check passes!"

  deploy:
    name: Deploy miden-vm mdbook
    runs-on: ubuntu-latest
    needs: check-files
    # Only run deployment on push to main/next branches, not on PRs
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@main

      - name: Install katex, alerts and linkcheck
        run: |
          rustup update --no-self-update stable
          cargo +stable install mdbook-katex mdbook-linkcheck mdbook-alerts

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build miden book
        run: mdbook build docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book/html
