# Runs build related jobs.

name: build

permissions:
  contents: read

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  no-std:
    name: Build for no-std
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - name: Build for no-std
        run: |
          rustup update --no-self-update ${{ matrix.toolchain }}
          rustup +${{ matrix.toolchain }} target add wasm32-unknown-unknown
          rustup default ${{ matrix.toolchain }}
          make build-no-std
  fuzz-check:
    name: Check for miden-core-fuzz crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        run: rustup toolchain install --no-self-update
      - uses: WarpBuilds/rust-cache@9d0cc3090d9c87de74ea67617b246e978735b1a1 # v2.9.1
        with:
          # We need to explicitly cache the miden-core-fuzz workspace, as only the root workspace is
          # cached by default.
          workspaces: |
            .
            miden-core-fuzz
      - name: Check miden-core-fuzz crate
        run: cd miden-core-fuzz && cargo check --locked
