name: test

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-ubuntu:
    name: test ${{matrix.toolchain}} on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
      - uses: taiki-e/install-action@nextest
      - name: Perform tests
        run: |
          rustup update --no-self-update ${{matrix.toolchain}}
          make test

  test-windows:
    name: Test Rust nightly on windows-2022
    # run windows check only when the target is `main`. will execute for release, push or PR.
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@main
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Perform tests
        run: make test

  test-windows-second:
    name: test ${{matrix.toolchain}} on windows-2022
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
      - uses: taiki-e/install-action@nextest
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Perform tests
        run: make test
